INSERT INTO articles (article_id, anotation, title, url) VALUES (1, 'Tragická nehoda autobusu se třemi mrtvými se stala na rovném úseku, který podle Horoměřických svádí k rychlosti a předjíždění. Horizont však přijde dřív, než by řidič čekal. Příčinu pátečního neštěstí policie zatím nezná, bude čekat na závěry znaleckých posudků. Nyní žádá svědky, aby jeho průběh pomohli objasnit.', 'Autobus u Horoměřic boural na zrádné rovince, která svádí k rychlosti', 'https://zpravy.idnes.cz/nehoda-autobus-horomerice-dcg-/krimi.aspx?c=A180113_100532_krimi_mav');
INSERT INTO articles (article_id, anotation, title, url) VALUES (6, 'Autobus se v pátek odpoledne na pomezí Prahy a Středočeského kraje nedaleko Horoměřic srazil s autem a následně narazil do stromu. Podle záchranné služby tři lidé zemřeli, zraněných je 45, z toho pět je ve vážném stavu. Mezi zraněnými jsou i děti.', 'U Prahy narazil autobus do stromu. Tři lidé zahynuli, mezi zraněnými jsou děti', 'https://www.novinky.cz/krimi/460383-u-prahy-narazil-autobus-do-stromu-tri-lide-zahynuli-mezi-zranenymi-jsou-deti.html');

INSERT INTO comments VALUES (2,	'Martin Jurečka', 'svádí řidiče silných vozů... spíše svádí řidiče slabé mysli',	1);
INSERT INTO comments VALUES (3,	'Jan Lavický', 'Řidiči autobusů bez psychotestů za volant nesednou.Mladé,sebevědomé slečně do silného auta sednout nikdo nezakáže.......', 1);
INSERT INTO comments VALUES (4,	'Jaromír Štohansl', 'Nemůžu si pomoct, ale jak vidím bílý Superb (nebo podobné bílé auto vyšší třídy) očekávám agresivního řidiče, který potřebuje být doma o 2 minuty dříve.Když k tomu přičtu nízký věk řidičky...nevím co se tam stalo, ale je větší šance, že je to klasická agresivní a arogantní jízda řidiče v bíle limuzíně.',	1);
INSERT INTO comments VALUES (5,	'Rostislav Vomáčka', 'Takže jezdí se tam 1350 km/h průměrné a nezapomeneme na to upozornit v nadpisu. Že se tam prakticky nebourá, to utopíme někde uprostřed článku.',	1);
INSERT INTO comments VALUES (7,	'Svatomír Novák',	'Chudáci stromy.Jeden zavazí šílenému policajtovi,druhý autobusákovi co ty stromy komu udělali?Není nad to,když za volantem sedí profesionálové.Ještě napíši,než dostanu mínusy,že mně se ještě nepodařilo žádný strom trefit.', 6);
INSERT INTO comments VALUES (8,	'Adam Morávek', 'Tak se ,,radaktore'' konečně rozhodněte, u Prahy, v Praze, nebo kde tedy opravdu? Úroveň pisálků z Novinek je v poslední době vážně žalostná. PS: účastníkům nehody (ať už se stala kdekoliv) přeji ať jsou v pořádku.',	6);
INSERT INTO comments VALUES (9,	'Miladka Uhlířová', 'Těm Pražákům se dneska daří Policajti do stromu autobusák do stromu Zeman se tam pokládá když ho ochranka přestane podpírt u voleb',	6);
INSERT INTO comments VALUES (10,	'Fake Fake', 'Za vsechno muze Sobotka a Kalousek',	1);
INSERT INTO comments VALUES (11,	'Taky Fake', 'Za vsechno muze Kalousek',	6);